# 需要合并的文件类型(xlsx or csv)
fileFormat: xlsx
# 是否合并表头(true:合并表头;false:不合并表头)
ifMergeHeader: false
# 需要合并的文件路径
filePath: E:\Desktop\GoMergeExcel\excel
# 合并好的文件保存路径
fileSavePath: E:\Desktop\GoMergeExcel\merge